_name: network_trainer
data_loaders:
  _name: s3n.fetch_data
  dataset: 
    _name: s3n.fgvc_dataset
    data_dir: ./datasets/CUB_200_2011
  batch_size: 16
  num_workers: 4
  transform:
    _name: image_transform
    image_size: [448, 448]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  train_augmentation:
    horizontal_flip: 0.5
    random_crop:
      scale: [0.5, 1]
  test_augmentation:
    center_crop: 448
  train_splits:
    - train
  test_splits:
    - test
log_path: './logs/CUB_baseline.log'
model:
  _name: s3n.ft_resnet
  mode: 'resnet50'
  num_classes: 200
criterion:
  _name: s3n.smooth_loss
  smooth_ratio: 0.85
optimizer:
  _name: s3n.sgd_optimizer
  lr: 0.01
  momentum: 0.9
  weight_decay: 1.0e-4
parameter:
  _name: finetune
  base_lr: 0.001
  groups:
    'classifier': 10.0
meters:
  top1:
    _name: s3n.topk_meter
    k: 1
  loss:
    _name: loss_meter
max_epoch: 30
device: cuda
hooks:
  on_start_epoch:
    -
      _name: update_lr
      epoch_list: [20,]
  on_end_epoch: 
    -
      _name: print_state
      formats:
        - 'epoch: {epoch_idx}'
        - 'train_loss: {metrics[train_loss]:.4f}'
        - 'test_loss: {metrics[test_loss]:.4f}'
        - 'train_top1: {metrics[train_top1]:.2f}%'
        - 'test_top1: {metrics[test_top1]:.2f}%'
    -
      _name: checkpoint
      save_dir: './generate/baseline/'
      save_step: 1